name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest + coverage
        run: |
          mkdir -p reports
          PYTHONPATH="$GITHUB_WORKSPACE" \
          pytest --junitxml=reports/junit.xml \
                 --cov=src \
                 --cov-report=xml:reports/coverage.xml \
                 --cov-report=term-missing

      - name: Upload reports (JUnit + coverage)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports
